apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    app: hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: omrisg/bottomline:hw
        ports:
        - containerPort: 8080
